name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v4
    
      - name: Instalar UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
    
      - name: Configurar o python ${{ env.PYTHON_VERSION }}
        run: uv python install ${{ env.PYTHON_VERSION }}
    
      - name: Instalar dependências
        run: uv sync --group dev

      - name: Lint com Ruff
        run: uv run ruff check src/ tests/ --output-format=github

      - name: Executar testes
        run: uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing
